image:
  file: .gitpod.Dockerfile
tasks:
  - name: Running MongoDB
    command: mongod --dbpath data
    # command: mkdir -p data && mongod --dbpath data
 - name: starting server
    command: npm start
#   - name: Install nodemon
#     command: npm i -g nodemon && npm start
